version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - technoshop
    env_file:
      - .env
    environment:
      - NGINX_PROXY=http://technoshop:${APP_PORT}
  technoshop:
    depends_on:
      - db
    build: .
    image: technoshop
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
  