# Generated by Django 4.2.6 on 2023-12-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_amount_item_quantity'),
        ('cart', '0004_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item')},
        ),
    ]
