# Generated by Django 4.2.6 on 2024-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_is_published'),
        ('cart', '0005_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart_items', through='cart.CartItem', to='products.item', verbose_name='Товары'),
        ),
    ]
