# Generated by Django 4.2.6 on 2024-01-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_default'),
        ('sales', '0002_alter_orderstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='Адрес'),
        ),
    ]
