# Generated by Django 4.2.6 on 2024-01-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_default'),
        ('sales', '0004_alter_order_order_status_delete_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address', verbose_name='Адрес'),
        ),
    ]
