# Generated by Django 4.2.6 on 2024-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=123, max_length=511, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
