# Generated by Django 4.2.6 on 2023-12-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_amount_alter_item_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='quantity',
        ),
    ]
