# Generated by Django 4.2.6 on 2024-01-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_chapter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.brand', verbose_name='Бренд'),
        ),
    ]
